@startuml
hide members
hide attributes
hide methods

state undefined
state defined
state circular
state final
final: object
state referenced
referenced: object

state "final (circular)" as final2
final2: object
state "referenced (circular)" as referenced2
referenced2: object

[*]         ->      undefined
undefined   ->      defined     : "#N="
undefined   -->     [*]         : end-of-input
defined     -down-> final       : "#N=(…)"
final       -down-> referenced  : "(…#N=(…)…#N#"
referenced  ->      referenced  : "(…#N=(…)…#N#…#N#"
final       -->     [*]         : end-of-input
referenced  -->     [*]         : end-of-input

defined     ->      circular    : "#N=(…#N#"
circular    ->      circular    : "#N=(…#N#…#N#"
circular    -down-> final2      : "#N=(…#N#…)"
final2      -down-> referenced2 : "(…#N=(…#N#…)…#N#"
referenced2 ->      referenced2 : "(…#N=(…#N#…)…#N#…#N#"
final2      -->     [*]         : end-of-input
referenced2 -->     [*]         : end-of-input

defined     ->      undefined   : "#N=#N#", recover
@enduml
